---
- hosts: monitoring
  roles:
    - role: sco.lvm_partition
      lvm_lvname: TSDB
      lvm_lvmount: /data
      lvm_lvsize: 8500
      lvm_lvfilesystem: xfs
      lvm_vgname: VolGroup00
      lvm_vgdevice: "/dev/vdb"
      
    - role: sco.prometheus
      become: true
      vars:
        prometheus_db_dir: "/data"
        prometheus_targets:
          node:
          - targets:
            - localhost:9100
      
    - role: sco.node-exporter
      become: true
      
    - role: sco.grafana
      become: true  