---
      
- name: install prometheus
  import_role:
    name: cloudalchemy.prometheus
  become: true
  vars:
    prometheus_db_dir: "/data/prometheus"
    prometheus_targets:
      node:
        - targets:
          - localhost:9100 #206.12.94.110
          #- 206-12-92-26.cloud.computecanada.ca:9100  #grafana server
          - omerocloud.med.ualberta.ca:9100           #206.12.92.91 UofA production server
          - 206-12-95-221.cloud.computecanada.ca:9100 # Training server
          - 206-12-94-73.cloud.computecanada.ca:9100  # National omero
          - 206-12-94-9.cloud.computecanada.ca:9100   # national omero backup
      prometheus-omero:
        - targets:
          - omerocloud.med.ualberta.ca:9449
          - 206-12-94-73.cloud.computecanada.ca:9449
          - 206-12-95-221.cloud.computecanada.ca:9449
      postgres:
        - targets:
          - omerocloud.med.ualberta.ca:9187
          - 206-12-94-73.cloud.computecanada.ca:9187
          - 206-12-95-221.cloud.computecanada.ca:9187

      django:
        - targets:
          - omerocloud.med.ualberta.ca/django_prometheus/metrics
          - 206-12-94-73.cloud.computecanada.ca/django_prometheus/metrics
          - 206-12-95-221.cloud.computecanada.ca/django_prometheus/metrics              
                         
            
- name: install alertmanager
  import_role:
    name: cloudalchemy.alertmanager
  vars:
    alertmanager_slack_api_url: 'https://hooks.slack.com/services/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'
    alertmanager_receivers:
      - name: slack
        slack_configs:
          - send_resolved: true
            channel: '#alerts'
    alertmanager_route:
      group_by: ['alertname', 'cluster', 'service']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 3h
      receiver: slack
  
    alertmanager_db_dir: "/data/alertmanager"
              
- name: install blacbox exporter
  import_role:
    name: cloudalchemy.blackbox-exporter
    
- name: install loki
  import_role:
    name: sco.loki
  become: true
  vars:
    loki_db_dir: "/data/loki"      

