---
- hosts: prometheus
  roles:
    - role: sco.lvm_partition
      lvm_lvname: TSDB
      lvm_lvmount: /data
      lvm_lvsize: 8500
      lvm_lvfilesystem: xfs
      lvm_vgname: VolGroup00
      lvm_vgdevice: "/dev/vdb"
      
    - role: sco.prometheus
      become: true
      vars:
        prometheus_db_dir: "/data"
        prometheus_targets:
          node:
          - targets:
            - localhost:9100
            - grafana.arbutus:9100
            - omero.med.ualberta.ca:9100
            - 206-12-95-221.cloud.computecanada.ca:9100
            - 206-12-94-73.cloud.computecanada.ca:9100
            - 206-12-94-9.cloud.computecanada.ca:9100
            

