---

- hosts: monitored
  roles:
    - role: cloudalchemy.node_exporter
      become: true

  tasks:
      - name: Create monitoring htpasswd
        become: yes
        copy:
          content: "{{ secret_monitoring_nginx_htpasswd | default(monitoring_nginx_htpasswd) }}"
          dest: /etc/nginx/monitoring.htpasswd
          mode: 0644

      # This is fine to apply to all servers because if an exporter doesn't
      # exist it will return an error, and we know which exporters to expect
      # when scraping
      - name: Create nginx proxy for prometheus exporters
        become: yes
        copy:
          dest: /etc/nginx/conf.d-nested-includes/proxy-exporters.conf
          src: confd-nested-proxy-exporters.conf
          mode: 0644
        notify:
        - restart nginx

  handlers:
    - name: restart nginx
      become: yes
      service:
        name: nginx
        state: restarted

  vars:
      # monitoring:monitoring
    monitoring_nginx_htpasswd: |
      monitoring:$apr1$njrafrtU$19wf/I15zPuSudlM5Y50Z0
      
      

- hosts: omero_server
  roles:
    - role: ome.prometheus_jmx
    
    # For restart handlers
    # and {{omero_common_basedir}} (normally /opt/omero)
    - role: ome.omero_common
    
    #sco.omero_prometheues_exporter works with Ubuntu20
    - role: sco.omero_prometheus_exporter
      vars:
        omero_prometheus_exporter_omero_user: omero-monitoring
        omero_prometheus_exporter_omero_password: omero-monitoring
        
    - role: sco.promtail
      become: true
      vars:
        loki_host: "206-12-92-26.cloud.computecanada.ca"
        loki_extra_scrape_configs:
          - job_name: "nginx"
            entry_parser: raw
            static_configs:
              - targets:
                  - localhost
                labels:
                  job: nginx
                  __path__: /var/log/nginx/*log
                  
          - job_name: "omero"
            static_configs:
              - targets:
                  - localhost
                labels:
                  job: omerologs
                  __path__: /opt/omero/server/OMERO.server/var/log/*.log
  
          - job_name: "postgres"
            static_configs:
              - targets:
                  - localhost
                labels:
                  job: postgreslogs
                  __path__: /var/log/postgres/*.log           
                     
  tasks:
    - name: omero-server prometheus jmx agents
      become: yes
      copy:
        dest: "{{ omero_common_basedir }}/server/config/prometheus.omero"
        src: omero-server-config-prometheus.omero
        mode: 0644
      notify:
      - restart omero-server    

- hosts: omero_web
  roles:
    - role: ome.omero_web_django_prometheus
    
  tasks:
  - name: Create nginx proxy for prometheus web exporters
    become: yes
    copy:
      dest: /etc/nginx/conf.d-nested-includes/proxy-exporters-web.conf
      src: confd-nested-proxy-exporters-web.conf
      mode: 0644
    notify:
    - restart nginx

  handlers:
  - name: restart nginx
    become: yes
    service:
      name: nginx
      state: restarted    
    

- hosts: omero_db               
  roles:
    - role: ome.prometheus_postgres
      prometheus_postgres_dbname: omero