---
# tasks file for rdiff-backup
# Installs rdiff-bakcup, librsync2 and dependencies
- hosts: backup_server
  tasks:
    - name: rdiff-backup | install rdiff-backup
      become: true
      apt:
        update_cache: true
        name: rdiff-backup
        state: present

    - name: rdiff-backup | create cron job
      become: true
      template:
        src: etc-crond-rdiff-backup.j2
        dest: /etc/cron.{{ rdiff_backup_frequency }}/rdiff-backup
        mode: 0755
        
        
  roles:
    - role: sco.lvm_partition
      lvm_lvname: backup
      lvm_lvmount: /backup
      lvm_lvsize: "{{ second_volume_size_gb }}"
      lvm_lvfilesystem: xfs
      lvm_vgname: VolGroup00
      lvm_vgdevice: "/dev/vdb"
        
