---
# ansible-playbook -i <INVENTORY-DIR>/prod-hosts site.yml

# New hosts are created in Compute Candada's openstack cloud
# infrastructure. requires a named cloud "computecanada_arbutus" that is defined in
# clouds.yaml file with authentication credentials specific for that cloud.
#Create Production Server
#- import_playbook: createInstance.yml
#  vars:
#    create_new_volume: True     
#    floating_ip: 206.12.92.91
#    flavour: "p8-12gb"
#    image: Ubuntu-20.04-Focal-x64-2020-12
#    server_name: "OMERO"
#    description: "University of Alberta's production OMERO server"
#    keypair: "SteveOKeyPairCCOMERO"
#    network: "def-steveogg-dev-network"
#    volume_name: "binary_repository"     
#    volume_size_gb: 100
#    device: "/dev/vdb"  # each flavor already has a 20Gb disk mounted on /dev/vda

#Create Training Server
#- import_playbook: createInstance.yml
#  vars:
#    create_new_volume: True     
#    floating_ip: 206.12.95.221
#    flavour: "p4-6gb"
#    image: Ubuntu-20.04-Focal-x64-2020-12
#    server_name: "OMERO Training"
#    description: "OMERO server used for training workshops"
#    keypair: "SteveOKeyPairCCOMERO"
#    network: "def-steveogg-dev-network"
#    volume_name: "binary_repository"     
#    volume_size_gb: 100
#    device: "/dev/vdb"  # each flavor already has a 20Gb disk mounted on /dev/vda

# deployment of xxx.med.ualberta.ca production OMERO.server. This is currently
# a one-node server hosting the db_server, omero_server and web_server from 
# a single instance
- import_playbook: productionServer.yml

# deployment of a training server. Single node
- import_playbook: trainingServer.yml

# Internal monitoring configuration for all OMERO servers
