---
# ansible-playbook -i <INVENTORY-DIR>/prod-hosts site.yml

# New hosts are created in Compute Candada's openstack cloud
# infrastructure. requires a named cloud "cc_arbutus_rep or cc_arbutus_default"
# that is defined in clouds.yaml file with authentication credentials specific
# for that cloud/project. Create Instance with optional second disk mounted on
# /dev/vdb to act as the OMERO binary repository.

#UofA production
#- import_playbook: createInstance.yml
#  vars:
#    cloud: cc_arbutus_default
#    create_second_volume: True     
#    floating_ip: 206.12.92.91
#    flavour: "p8-12gb"
#    image: Ubuntu-20.04-Focal-x64-2020-12
#    server_name: "OMERO"
#    description: "University of Alberta's production OMERO server"
#    keypair: "SteveOKeyPairCCOMERO"
#    network: "def-steveogg-dev-network"
#    volume_name: "binary_repository"     
#    volume_size_gb: 100
#    device: "/dev/vdb"
# # instance defined to boot from a 100Gb disk mounted on /dev/vda

#Create Training Server
#- import_playbook: createInstance.yml
#  vars:
#    cloud: cc_arbutus_default
#    create_second_volume: True     
#    floating_ip: 206.12.95.221
#    flavour: "p4-6gb"
#    image: Ubuntu-20.04-Focal-x64-2020-12
#    server_name: "OMERO Training"
#    description: "OMERO server used for training workshops"
#    keypair: "SteveOKeyPairCCOMERO"
#    network: "def-steveogg-dev-network"
#    volume_name: "binary_repository"     
#    volume_size_gb: 100
#    device: "/dev/vdb"
# # instance defined to boot from a 100Gb disk mounted on /dev/vda

#Create National Production Server
#- import_playbook: createInstance.yml
#  vars:
#    cloud: cc_arbutus_rpp
#    create_second_volume: True     
#    floating_ip: 206.12.94.73
#    flavour: "p16-24gb"
#    image: Ubuntu-20.04-Focal-x64-2020-12
#    server_name: "National OMERO"
#    boot_volume_size: 200
#    #server_description: "Canadian National production OMERO server"
#    keypair: "SteveOKeyPairCCOMERO"
#    network: "rpp-steveogg-network"
#    volume_name: "binary_repository"     
#    second_volume_size_gb: 20000
#    volume_description: "Volume to use as the OMERO binary repository"
#    device: "/dev/vdb"
#    security_group_list:
#      - default
#      - web
#      - ping
#      - omero
#      - ssh
       
# # instance defined to boot from a 100Gb disk mounted on /dev/vda

#Create Development Server
#- import_playbook: createInstance.yml
#  vars:
#    cloud: cc_arbutus_rpp
#    create_second_volume: True     
#    floating_ip:
#    flavour: "p4-6gb"
#    image: Ubuntu-20.04-Focal-x64-2020-12
#    server_name: "OMERO Development"
#    description: "OMERO server used to test new functionality"
#    keypair: "SteveOKeyPairCCOMERO"
#    network: "rpp-steveogg-network"
#    volume_name: "binary_repository"     
#    volume_size_gb: 100
#    device: "/dev/vdb"
# # instance defined to boot from a 100Gb disk mounted on /dev/vda

# Configure National OMERO.server. This is currently
# a one-node server hosting the db_server, omero_server and web_server from 
# a single instance.

- name: Install OMERO and configure
  import_playbook: productionServer.yml
  vars:
    fqdn: "206-12-94-73.cloud.computecanada.ca"
 
#- hosts: omero
#  import_playbook: productionServer.yml
#  vars:
#    fqdn: "omerocloud.med.ualberta.ca"   


# deployment of a training server. Single node
#- import_playbook: trainingServer.yml

# Internal monitoring configuration for all OMERO servers
