---

- hosts: omero
  tasks:
  
    - name: install mmdb reader repository
      become: true
      apt_repository:
        repo: ppa:maxmind/ppa

    - name: install C library for reading MaxMind DB files
      become: true
      apt:
        update_cache: true
        name: ['libmaxminddb0', 'libmaxminddb-dev', 'mmdb-bin']
        
  
    # (Total cores / 2), leaving some for WSGI
    - name: NGINX - Performance tuning - worker processes
      become: true
      replace:
        dest: "/etc/nginx/nginx.conf"
        regexp: '^worker_processes\s+\d+;'
        replace: "worker_processes {{ ((ansible_processor_count * ansible_processor_cores) / 2) |round|int }};"

    # cf https://www.digitalocean.com/community/tutorials/how-to-optimize-nginx-configuration
    - name: NGINX - Performance tuning - worker connections
      become: true
      replace:
        path: "/etc/nginx/nginx.conf"
        regexp: 'worker_connections\s+\d+;'
        replace: "worker_connections 1024;"
        
    # Workaround lack of restriction on temp file sizes
    # https://github.com/ome/omero-web/issues/118
    # The downside is that it won't be automatically cleared out 
#    - name: Create another temporary directory since OMERO doesn't limit sizes and fills up /tmp
#      become: true
#      file:
#        path: "{{ omero_server_systemd_environment.OMERO_TMPDIR }}"
#        state: directory
#        mode: 0700
#        owner: "{{ omero_server_system_user }}"

    - name: copy ngx_http_geoip2_module.so to server
      become: true
      copy:
        src: ngx_http_geoip2_module.so
        dest: /usr/lib/nginx/modules/
        group: root
        owner: root
        mode: 0644
              
    - name: edit nginx.conf to load ngx_http_geoip2_module.so
      become: true
      lineinfile:
        path: /etc/nginx/nginx.conf
        line: load_module modules/ngx_http_geoip2_module.so;
        insertbefore: 'events {'
        
    - name: edit nginx.conf to map variables to mmdb data
      become: true
      blockinfile:
        path: /etc/nginx/nginx.conf
        insertbefore: 'sendfile on;'
        block: |
          geoip2 /etc/geolite/GeoLite2-Country.mmdb {
          auto_reload 5m;
          $geoip2_metadata_country_build metadata build_epoch;
          $geoip2_data_country_code country iso_code;
          $geoip2_data_country_name country names en;
          }
          geoip2 /etc/geolite/GeoLite2-City.mmdb {
          $geoip2_data_city_name city names en;
          }
          
          
          
          
          
          
          
