---
- hosts: omero, national-omero
  vars:
    omero_prometheus_tools_version: 0.2.0

    omero_prometheus_tools_requirements_ice_package:
     RedHat:
       7: "https://github.com/ome/zeroc-ice-py-centos7/releases/download/\
         0.2.1/zeroc_ice-3.6.5-cp36-cp36m-linux_x86_64.whl"
       8: "https://github.com/ome/zeroc-ice-centos8/releases/download/\
         0.0.1/zeroc_ice-3.6.5-cp36-cp36m-linux_x86_64.whl"
     Debian:
       18: "https://github.com/ome/zeroc-ice-ubuntu1804/releases/download/\
          0.2.0/zeroc_ice-3.6.5-cp36-cp36m-linux_x86_64.whl"
       20: "https://github.com/ome/zeroc-ice-ubuntu2004/releases/download/\
          0.2.0/zeroc_ice-3.6.5-cp38-cp38-linux_x86_64.whl"

# List of python3 packages to install
    omero_prometheus_tools_requirements:
  # TODO: make the use of our non-standard wheel optional
      - "{{ omero_prometheus_tools_requirements_ice_package[ansible_os_family][ansible_distribution_major_version | int] |
          default('zeroc-ice')}}"
      - omero-py==5.9.1
      - "omero-prometheus-tools=={{ omero_prometheus_tools_version }}"

  tasks:
  
    - name: omero prometheus exporter | install omero-prometheus-tools
      become: true
      pip:
        name: "{{ omero_prometheus_tools_requirements }}"
        state: present
        virtualenv: /opt/prometheus-omero-tools/venv3
        virtualenv_command: /usr/bin/python3 -m venv