---
- name: Create/Configure UofA production instance
  hosts: uofa_omero
  gather_facts: false
  tasks:
    - name: create the instance in the cloud
      import_role:
        name: sco.create_instance
      vars:
        cloud: cc_arbutus_default_dev
        create_second_volume: true
        floating_ip: 206.12.92.91
        flavour: "p8-12gb"
        image: Ubuntu-20.04-Focal-x64-2020-12
        # description: "University of Alberta's production OMERO server"
        # current version of openstack.cloud.server or maybe the python openstacksdk fails 
        # when provided with any description. 20210430
        boot_volume_size: 200
        server_name: "omero"
        keypair: "SteveOKeyPairCCOMERO"
        network: def-steveogg-dev-network
        security_group_list:
          - default
          - web
          - ssh
          - ping
          - omero
          - monitoring
        second_volume_name: "binary_repository"
        second_volume_size_gb: 9500
        second_volume_description: "/OMERO binary repository"
        device: "/dev/vdb"
      delegate_to: localhost
 
        
- name: configure the newly created instance
  import_playbook: productionServer.yml