---
- hosts: grafana
  become: true
  vars:
    cert_domain: 206-12-92-26.cloud.computecanada.ca
  tasks:
    - name: grafana | edit /etc/grafana/grafana.ini change protocol to https
      lineinfile:
        path: /etc/grafana/grafana.ini
        backrefs: true
        regexp: '(protocol = http)'
        line:   '\1s' 
        state: present
                   

    - name: grafana | edit /etc/grafana/grafana.ini change port to 443
      lineinfile:
        path: /etc/grafana/grafana.ini
        backrefs: true
        regexp: '(http_port =)'
        line:    '\1 443' 
        state: present     

    - name: grafana | edit /etc/grafana/grafana.ini change domain
      lineinfile:
        path: /etc/grafana/grafana.ini
        backrefs: true
        regexp: '(domain =) \w{9,}'
        line:    '\1 {{ cert_domain }}'
        state: present
    
    - name: grafana | edit /etc/grafana/grafana.ini change add https://domain
      lineinfile:
        path: /etc/grafana/grafana.ini
        backrefs: true
        regexp: '(root_url =)'
        line:    '\1 https://{{ cert_domain }}'
        state: present

    - name: grafana | edit /etc/grafana/grafana.ini add cert location
      lineinfile:
        path: /etc/grafana/grafana.ini
        insertbefore: '^;cert_file'
        firstmatch: yes
        line: 'cert_file = /etc/letsencrypt/live/{{cert_domain}}/fullchain.pem'
        state: present       

    - name: grafana | edit /etc/grafana/grafana.ini add key location
      lineinfile:
        path: /etc/grafana/grafana.ini
        backrefs: true
        regexp: '(cert_key =)'
        line: '\1 /etc/letsencrypt/live/{{cert_domain}}/privkey.pem'
        state: present  
    