---
- hosts: grafana
  tasks:
  
    - name: configure grafana
      import_role:
        name: sco.grafana
      become: true
      vars:
        cert_domain: "206-12-92-26.cloud.computecanada.ca"
      
